data:
  num_workers: 8
  train_dataset: /data/datasets/cifar/cifar_train.beton
  val_dataset: /data/datasets/cifar/cifar_test.beton
training:
  batch_size: 512
  epochs: 150
  lr: 0.5
  momentum: 0.9
  lr_peak_epoch: 5
  weight_decay: 5e-4
  label_smoothing: 0.1
  lr_tta: true
  num_workers: 8
gsr:
  nonzero: 8
  groupsize: 16
  prune_type: 'maxnorm'
