data:
  in_memory: 1
  num_workers: 16
  train_dataset: /data/datasets/ffcv/train_448_0.60_90.ffcv
  val_dataset: /data/datasets/ffcv/val_448_0.60_90.ffcv
dist:
  world_size: 4
logging:
  folder: /tmp/
lr:
  lr: 1.0
  lr_peak_epoch: 2
  lr_schedule_type: cyclic
model:
  arch: resnet18
resolution:
  end_ramp: 76
  max_res: 192
  min_res: 160
  start_ramp: 65
training:
  batch_size: 1024
  bn_wd: 0
  distributed: 1
  epochs: 88
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 1
validation:
  lr_tta: true
  resolution: 256
gsr:
  nonzero: 2
  groupsize: 4
  prune_type: 'max'
